//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string name { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public Nullable<decimal> price { get; set; }
        public int id { get; set; }
    }
}
